/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package step2;

import java.io.IOException;
import org.apache.commons.cli.ParseException;
import step2.services.FilterService;
import step2.utils.CommandLineParser;
import step2.utils.MovieFile;

/**
 * Entry point for the application.
 */
public class App {
    public static void main(String[] args) {
        var commandLineParser = new CommandLineParser();
        try {
            commandLineParser.parseInputs(args);
            var movies = MovieFile.read("../data/movies.json");
            FilterService fs = new FilterService();
            var filtered = fs.getMoviesByDecade(movies, commandLineParser.getDecade());
            MovieFile.write(commandLineParser.getOutputFile(), filtered);

        } catch (ParseException | IOException | RuntimeException ex_) {
            System.out.println("Error: " + ex_);
            commandLineParser.printHelp();
            System.exit(1);
        }
    }
}
