/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package step3;

import java.io.IOException;
import org.apache.commons.cli.ParseException;
import step3.services.RelationsService;
import step3.utils.CommandLineParser;
import step3.utils.MovieFile;

/**
 * Entry point for the application.
 */
public class App {
    public static void main(String[] args) {
        var commandLineParser = new CommandLineParser();
        try {
            commandLineParser.parseInputs(args);
            var movies = MovieFile.read("../data/80s-movies.json");
            RelationsService fs = new RelationsService();

            if(isNullOrEmpty(commandLineParser.getNameOne())) {
                throw new IllegalArgumentException("Must supply at least one name!");
            }
            else if(isNullOrEmpty(commandLineParser.getNameTwo())) {
                fs.getDegreesOfKevinBacon(movies, commandLineParser.getNameOne());
            }
            else {
                fs.getDegrees(movies, commandLineParser.getNameOne(), commandLineParser.getNameTwo());
            }

//            fs.getDegreesOfKevinBacon(movies, "Adrienne King");
//            fs.getDegrees(movies, "Tom Cruise",  "Kevin Bacon");
        } catch (ParseException | IOException | RuntimeException ex_) {
            System.out.println(ex_.getMessage());
            ex_.printStackTrace();
            System.exit(1);
        }
    }

    private static boolean isNullOrEmpty(String s) {
        return s == null || s.isEmpty();
    }
}
