/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package step2;

import java.util.Collection;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import step2.models.Movie;
import step2.services.FilterService;
import step2.utils.MovieFile;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class FilterTests {

    private Collection<Movie> movies;

    @BeforeEach
    public void readMovies() throws Exception {
        movies = MovieFile.read("../data/movies.json");
        assertEquals(movies.size(), 28796);
    }

    @Test
    public void filterTest() {
        var fs = new FilterService();
        var filtered = fs.getMoviesByDecade(movies, 80);
        assertEquals(filtered.size(), 1987);
    }
}
